### PR TITLE
Make part url fully qualified even if INVENTREE_BASE_URL is not set ( Fix #41 )

### LINKED ISSUE #41: Part URL is not fully qualified
When creating a symbol in KiCad, the Part URL is not fully qualified.
image
image

### PR DESCRIPTION
**Pull request by 30350n**
This fixes #41.

### CODE REVIEW

**Comment by afkiwers** [comment]
@SchrodingersGat wasn't there a legacy issue? Not sure if the whole block can be replaced.

**Comment by 30350n** [comment]
Well seemingly `construct_absolute_url` was only moved to `helpers_model` in 0.12.9. So if you want to support earlier versions that's problematic. You have the exact same issue with the current code though, because with how things are atm `if 'request' in self.context:` is always `False`, because the `request` never gets added.

**Comment by afkiwers** [comment]
I guess we need to discuss this in a bit more detail before we merge this. :-)

**Comment by SchrodingersGat** [comment]
You could potentially inspect the inventree version first to determine where to import from?

**Comment by 30350n** [comment]
Actually, just checked again and I was wrong before. `construct_absolute_url` got moved in [this](https://github.com/inventree/InvenTree/commit/99d122baa9afbe924922df9cc49ae22077391da4) commit and the `request` kwarg got added [here](https://github.com/inventree/InvenTree/commit/61d613ff34d3c3491baa8f25e1a0f49cb98c3c30). Both of these commits actually are pre 0.12.0, so as long as you don't want to support 0.11 or earlier, this should work.

**Comment by SchrodingersGat** [comment]
Yeah that is reasonable, 0.11.x is pretty old now

**Comment by afkiwers** [comment]
@SchrodingersGat I am happy to merge it if you are. 

I'll also change the min InvenTree version to 0.12.x once I have some time.

**Comment by SchrodingersGat** [comment]
I'm happy!

**Comment by afkiwers** [comment]
@30350n thank you very much for your contribution :-)

**Comment by 30350n** [comment]
Thanks for merging! :)

**Pull request merged**
